# Generated by Django 3.1.2 on 2020-10-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=255, verbose_name='CC')),
                ('en_name', models.CharField(max_length=255, null=True, verbose_name='英語名称')),
                ('image', models.ImageField(blank=True, max_length=192, null=True, upload_to='static/images/cc/', verbose_name='画像')),
            ],
            options={
                'verbose_name': 'クリエイティブコモンズ',
                'verbose_name_plural': 'クリエイティブコモンズ',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.ImageField(null=True, upload_to='static/images/media', verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cc_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.ccsetting', verbose_name='CC設定')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='_work_collaborators_+', to=settings.AUTH_USER_MODEL, verbose_name='コラボレーター')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('images', models.ManyToManyField(related_name='media', to='works.MediaImage', verbose_name='画像')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likers', to='works.work')),
                ('liker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'イイネ関係',
                'verbose_name_plural': 'イイネ関係',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('commentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_comments', to=settings.AUTH_USER_MODEL, verbose_name='コメンター')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.comment', verbose_name='親コメント')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='works.work', verbose_name='作品')),
            ],
        ),
    ]
