# Generated by Django 3.1.2 on 2020-10-17 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.comment', verbose_name='親コメント'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likers', to='works.work', verbose_name='作品'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
