# Generated by Django 3.1.2 on 2020-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20201017_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='is_public',
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('public', '公開'), ('private', '非公開')], default='draft', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='ccsetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/cc/', verbose_name='画像'),
        ),
    ]
