# Generated by Django 3.1.2 on 2020-10-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20201025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='uri',
            field=models.ImageField(max_length=255, null=True, upload_to='static/images/media', verbose_name='URI'),
        ),
    ]
