# Generated by Django 3.1.2 on 2020-11-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20201029_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.FileField(max_length=255, null=True, upload_to='static/sounds', verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='sounds',
            field=models.ManyToManyField(related_name='sound', to='works.MediaSound', verbose_name='サウンド'),
        ),
    ]
