# Generated by Django 3.1.2 on 2020-11-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20201110_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ'),
        ),
    ]
