# Generated by Django 3.1.2 on 2020-10-17 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201017_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='表示する'),
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='表示順序'),
        ),
    ]
