# Generated by Django 3.1.2 on 2020-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201025_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='genre_str',
            field=models.CharField(blank=True, max_length=192, null=True, verbose_name='ジャンル表示'),
        ),
    ]
