# Generated by Django 3.1.2 on 2020-10-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_member_genre_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=255, upload_to='static/images/avatar', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/images/avatar', verbose_name='アバタ'),
        ),
    ]
