# Generated by Django 3.1.2 on 2020-11-02 22:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201029_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='static/images/avatar', verbose_name='アバタ'),
        ),
    ]
