# Generated by Django 3.1.2 on 2020-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_used_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='used_amount',
            field=models.IntegerField(default=0, verbose_name='使用容量'),
        ),
    ]
