# Generated by Django 3.1.2 on 2020-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20201029_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_str',
            field=models.CharField(default='', max_length=50, verbose_name='ルーム'),
        ),
    ]
