# Generated by Django 3.1.2 on 2020-10-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_room_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/images/message', verbose_name='画像'),
        ),
    ]
